receivers:
  filelog:
    include:
      - ./otlp-all.json
    start_at: beginning

exporters:
  debug:
    use_internal_logger: false
    verbosity: detailed
  elasticsearch:
    endpoints:
      - https://5fe4c23ab2c74f179029ef4760828720.us-west2.gcp.elastic-cloud.com:443
    compression: none
    user: elastic
    password: tUueGhhfDgwc0mRcu1xlQ5sS
    logs_dynamic_index:
      enabled: true
    batcher:
      enabled: true
      flush_timeout: 1s

processors:
  batch:
  transform:
    log_statements:
      - context: log
        statements: 
          - set(attributes["data_stream.namespace"], "default")
          - set(attributes["data_stream.dataset"], "otel")          

service:
  pipelines:
    logs:
      receivers: [filelog]
      processors: [transform, batch]
      exporters: [elasticsearch, debug]